# <font color='blue'>MAI5002 - Fundamentos de Matemática Aplicada</font>

## Primeira Avaliação 02/10/2020

### Prof. Luis Gustavo Nonato  

ICMC-USP

----

<font color='red'> Não esqueça de renomear o arquivo com seu nome e número USP antes de fazer upload no Drive. <br><br>Por exemplo: <br><br> **Gustavo_Nonato_3223813.ipynb** <br><br> Insira também seu nome e número USP na célula abaixo.</font>

---

**Nome: Bruno Fernandes Bessa de Oliveira** 

**\#USP: 5881890** 

---

## <font color='blue'> Instruções para Avaliação 1</font>
<font color='blue'> Os seguintes passos devem ser seguidos para realizar a avaliação:

1. Assine a lista de presença disponível no arquivo `lista de presenca` disponível no arquivo que está no diretório _Avaliacao1/Entregas da Avaliacao_ do repositório Google Drive
2. Baixe e renomeie o notebook `MAI5002 avaliacao 1.ipynb` com seu nome e número USP
3. Uma vez que tenha concluído a avaliação, faça upload do notebook (renomeado) no diretório _Avaliacao1/Entregas da Avaliacao_

O diretório _Avaliacao1/Entregas da Avaliacao_ estará aberto para upload até as 17h do dia 04/10, após esta data e horário não será possível fazer o upload.

Nas questões 1), 2) e 3) você precisa marcar a alternariva correta e também incluir o código Python que calcula o resultado da questão. Para marcar a alternativa que julgue correta, inclua um sinal (X) na frente da mesma. Por exemplo:

a) 123<br>
b) 234 (X)<br>
c) 345<br>
d) 456

Todas as questões da prova valem 2 pontos.
</font>

### Exercício 1) 
Considere a transformação linear dada pela matriz 

$$
\left(\begin{array}{ccccccc}
3 & 8 & 4 & 4 & 6 & 0 & 6 & 0 & 6\\
3 & 4 & 5 & 2 & 6 & 0 & 0 & 5 & 6\\
2 & 2 & 1 & 1 & 4 & 4 & 3 & 0 & 3\\
0 & 6 & 8 & 3 & 0 & 0 & 3 & 4 & 6
\end{array}\right)
$$

1.1) Qual a dimensão do espaço linha da matriz?<br>
a) 3<br>
b) 4 (X) <br>
c) 5<br>
d) 6

1.2) Qual a dimensão do núcleo da transformação?<br>
a) 3<br>
b) 4<br>
c) 5 (X) <br>
d) 6

**OBS**: Escreva um código ou argumentos que confirmem as respostas dadas acima.

In [1]:
import numpy as np

A = np.asarray([[3, 8, 4, 4, 6, 0, 6, 0, 6],
                [3, 4, 5, 2, 6, 0, 0, 5, 6],
                [2, 2, 1, 1, 4, 4, 3, 0, 3],
                [0, 6, 8, 3, 0, 0, 3, 4, 6]])

A transformação <b>A</b> possui dimensões (4x9). O seu espaço imagem (espaço coluna) é gerado pelos vetores coluna. Somente vetores LI podem gerar um espaço. Logo, neste caso temos no máximo r=4 vetores coluna LI para a transformação <b>A</b>.

Abaixo tomamos uma seleção arbitrária de 4 colunas (formando a matriz $\mathbf{A}_4$) e calculamos seu determinante, que é diferente de 0, provando que há 4 vetores coluna na matriz <b>A</b>.


In [32]:
A4 = np.asarray([[3, 8, 4, 0],
                 [3, 4, 5, 0],
                 [2, 2, 1, 4],
                 [0, 6, 8, 0]])

print(np.linalg.det(A4))

455.9999999999998


Sendo assim, dim(C(A)) = 4: a dimensão do espaço linha da matriz é 4.

O Teorema do Núcleo e da Imagem nos garante que: <br>
dim($\mathcal{N}$(A)) + dim(C(A)) = k = 9 <br><br>
Logo: dim($\mathcal{N}$(A)) = 5: a dimensão do núcleo da transformação é 5

### Exercício 2)
Considere a função $f(x)=x^2\cos(4x^2)$, $x\in[0,1]$. Usando o método dos mínimos quadrados, aproxime a função $f(x)$ por um polinômio cúbico. Para calcular a aproximação, discretize o intervalo $[0,1]$ em 100 pontos igualmente espaçados (utilize o método <font color='blue'> linspace </font> do numpy). Qual o valor aproximado do polinômio no ponto $x=0.25$?

a) 0.000<br>
b) 0.127 (x)<br>
c) 0.225<br>
d) 0.060

Inclua abaixo o código python que calcula a solução.

In [27]:
# Gerando os pontos do domínio da função e da imagem conforme a restrição:
x = np.linspace(0,1,100)
f = (x**2)*np.cos(4*x**2)

# O polinômio cúbico será dado por:
A = np.ones((x.shape[0],4))
A[:,1] = x
A[:,2] = x**2
A[:,3] = x**3

Na célula acima temos a função f(x) e os três graus do polinômio cúbico a ser ajustado, sendo que as colunas da matriz A formam um espaço. A aproximação da função f, com o conjunto de coeficientes a conveniente pode ser escrita de forma matricial:<br>
$$
\mathbf{A}^\top\mathbf{A}\mathbf{\alpha}=\mathbf{A}^\top\mathbf{f}
$$

In [29]:
alpha = np.linalg.solve(np.dot(A.T,A),np.dot(A.T,f))

x_teste = 0.25
f_aprox = (alpha[0]
           + alpha[1]*x_teste
           + alpha[2]*x_teste**2
           + alpha[3]*x_teste**3)

print('O valor aproximado da função pelo polinômio no ponto x={x_teste} é {f_aprox:.4f}.'
      .format(x_teste=x_teste, f_aprox=f_aprox))

O valor aproximado da função pelo polinômio no ponto x=0.25 é 0.1276.


### Exercício 3)
Considere o subespaço $S$ gerado pelos vetores 
$$
\mathbf{u_1} = \left[\begin{array}{c}
                3 \\ 4 \\ 4 \\ 6 \\ 1
                \end{array}\right] \qquad               
\mathbf{u_2} = \left[\begin{array}{c}
                7 \\ 1 \\ 0 \\ 2 \\ 1
                \end{array}\right]
$$

A projeção do ponto $(4, 8, 7, 4, 3)$ no subespaço $S$ é aproximadamente: 

a) [1.29 -0.03]<br>
b) [8.02 6.31]<br>
c) [5.58 4.72 2.79 4.53 4.02]<br>
d) [3.62 5.11 5.14 7.65 1.25] (X)

**Obs**: Inclua abaixo um código que calcula a projeção.

Devemos encontrar uma base ortonormal para o subespaço $S$. Para tanto, Usemos o método de fatoração QR, implementado numericamente pela biblioteca numpy.

In [5]:
# Solução
u1 = np.array([3, 4, 4, 6, 1])
u2 = np.array([7, 1, 0, 2, 1])

A = np.array([u1, 
              u2]).T

q, r = np.linalg.qr(A)

p  = np.array([4, 8, 7, 4, 3])
proj = np.dot(q.T[0],p)*q.T[0] + np.dot(q.T[1],p)*q.T[1]
print('A projeção é: {}'.format(proj))

A projeção é: [3.6208714  5.10892481 5.14265636 7.64652143 1.25193254]


### Exercício 4)
Encontre uma base ortonormal que gere o espaço dado pela equação $x-2y+z-w=0$.

**Dica**: A equação dá origem a um subspaço de dimensão 3 em $\mathbf{R}^4$. Encontre uma base que gere o espaço e aplique Gram-Schmidt para ortonormalizar a base encontrada.

Vamos deixar um termo em função dos demais na equação dada.
$$
x = 2y -z + w 
$$
De modo que pontos neste espaço estão dados pelos vetores:
$$
y[2, 1, 0, 0]^T + z[-1, 0, 1, 0]^T + w[1, 0, 0, 1]^T
$$
E os vetores que geram este espaço são:
$$
\mathbf{u_1} = [2, 1, 0, 0]^T \\
\mathbf{u_2} = [-1, 0, 1, 0]^T \\
\mathbf{u_3} = [1, 1, 0, 1]^T 
$$
O método de Gram-Shimidt consiste em encontrar uma base ortonormal projetando cada um dos vetores de entrada em um espaço através de produto interno. Usaremos a implementação do método em Python que recebe a matriz cujas linhas são os vetores de entrada.  

In [6]:
# Implementação do método de Gram-Shimidt conforme material de aula:
def gram_schmidt(x):
    q = np.zeros(x.shape)  # matriz cujas colunas são os elementos da base ortonormal
    
    q[:,0] = x[:,0]/np.linalg.norm(x[:,0]) # primeiro elemento da base
    for i in range(1,x.shape[1]):  # indice das colunas da base x
        coefs = np.array([np.dot(x[:,i].T,q[:,j]) for j in range(i)]).reshape(-1,1) # gera os coeficiente <x_i.T,q_j>
                                                                                    # e guarda em um vetor coluna
        q[:,i:i+1] = x[:,i:i+1] - np.dot(q[:,:i],coefs)
        q[:,i] = q[:,i]/np.linalg.norm(q[:,i])
        
    return(q)

In [7]:
# Solução

u1 = np.array([ 2, 1, 0, 0])
u2 = np.array([-1, 0, 1, 0])
u3 = np.array([ 1, 1, 0, 1])

A = np.array([u1,
              u2,
              u3]).T

Q = gram_schmidt(A)
print('A base ortonormal encontrada pelo método é:\n {}'.format(Q))

A base ortonormal encontrada pelo método é:
 [[ 0.89442719 -0.18257419 -0.15430335]
 [ 0.4472136   0.36514837  0.3086067 ]
 [ 0.          0.91287093 -0.15430335]
 [ 0.          0.          0.9258201 ]]


Para mostrar que trata-se de uma base ortonormal, vamos mostrar que vale a seguinte propriedade: $\mathbf{Q}\mathbf{Q}^\top=\mathbf{I}$, sendo <b>I</b> a matriz identidade. 

In [8]:
np.set_printoptions(precision=2,suppress=True)
print(np.dot(Q.T,Q))

[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


### Exercício 5)
**5.1)**<br> 
Construa uma transformação linear $\mathbf{A}:\mathbb{R}^5\rightarrow\mathbb{R}^3$ tal que os vetores 

$$
\mathbf{v}_1 = \begin{bmatrix} 1 \\ 1 \\ 0 \\ 1 \\ 1\end{bmatrix}\quad
\mathbf{v}_2 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 0 \\ 1\end{bmatrix}\quad
\mathbf{v}_3 = \begin{bmatrix} 0 \\ 0 \\ 1 \\ 1 \\ 0\end{bmatrix}
$$

gerem o espaço nulo e os vetores 

$$
\mathbf{u}_1 = \begin{bmatrix}  0 \\ 1 \\ 1\end{bmatrix}\quad
\mathbf{u}_2 = \begin{bmatrix}  1 \\ 0 \\ 1\end{bmatrix}
$$

gerem o espaço coluna. 

**5.2)**<br>
Verifique que sua resposta está correta aplicando a transformação $\mathbf{A}$  em uma combinação linear qualquer dos vetores $\mathbf{v}_1$, $\mathbf{v}_2$ e $\mathbf{v}_3$, o que deve resultar em um vetor nulo (zero). 

**5.3)**<br>
Verifique ainda que qualquer vetor mapeado por $\mathbf{A}$ é uma combinação linear de $\mathbf{u}_1$ e $\mathbf{u}_2$.

**Dicas**: 
1. Para encontrar a transformação garantindo que os vetores $\mathbf{v}_1$, $\mathbf{v}_2$ e $\mathbf{v}_3$ estão no espaço nulo, você terá que resolver um sistema de equações com dois graus de liberdade. Utilize os graus de liberdade para garantir que os vetores $\mathbf{u}_1$ e $\mathbf{u}_2$ estão no espaço coluna.

2. Para verificar que todo vetor mapeado pela transformação $\mathbf{A}$ está no espaço gerado por $\mathbf{u}_1$ e $\mathbf{u}_2$, verifique que a projeção de um ponto mapeado sobre o espaço gerado por $\mathbf{u}_1$ e $\mathbf{u}_2$ é o próprio ponto.

Se os vetores $\mathbf{v}_1, \mathbf{v}_2, \mathbf{v}_3$ geram o espaço nulo a partir de $\mathbb{R}^5$, sendo k = 5 o número de entrada destes vetores, devemos encontrar mais 2 vetores (quantidade obtida do Teorema do Núcleo e da Imagem) em $\mathbb{R}^5$ para a transformação A que sejam LI. <br>
Para encontrar esses vetores que formam a transformação A $\mathbf{a}_1$ e $\mathbf{a}_2$ vamos crir um sistema de equações com o argumento de ortonormalidade:

$$
<\mathbf{a}_i|\mathbf{a}_j> = \mathbf{\delta}_{ij} \\
<\mathbf{a}_{1,2}|\mathbf{v}_1> = 0 \\
<\mathbf{a}_{1,2}|\mathbf{v}_2> = 0 \\
<\mathbf{a}_{1,2}|\mathbf{v}_3> = 0 \\
$$

Tomemos $\mathbf{a}=[a b c d e]^{T}$. Ao escevermos estas condições teremos um sistema linear de 10 incógnitas e 8 equações, resultando em 2 termos livres.

Sendo assim, aplicando a ortogonalidade de $\mathbf{a}_i$ com os vetores do espaço nulo:
$$
a + b + 0 + d + e = 0 \\
a + 0 + c + 0 + e = 0 \\
0 + 0 + c + d + 0 = 0 \\
$$
Logo:
$$
a = d - e \\
b = -2d \\
c = -d \\
d = d \\
e = e \\
$$
E temos os vetores $\mathbf{a}$ escritos com a seguinte base:
$$
\mathbf{a} = d{[1, -2, -1, 1, 0]}^{T} + e{[-1, 0, 0, 0, 1]}^{T} \\
\mathbf{a}_1 = [1, -2, -1, 1, 0]^{T} \\
\mathbf{a}_2 = [-1, 0, 0, 0, 1]^{T}
$$
Além destes vetores (que são LI), para que a transformação mapeie em $\mathbb{R}^3$ é necessário mais um vetor LD com relação aos dois primeiros encontrados. Isso não altera a dimensão do espaço. Escolhemos $\mathbf{a}_3 = \mathbf{a}_1 - \mathbf{a}_2$.
Abaixo mostramos que vale a ortogonalidade:

In [9]:
v1 = np.array([1,1,0,1,1])
v2 = np.array([1,0,1,0,1])
v3 = np.array([0,0,1,1,0])

a1 = np.array([ 1,-2,-1, 1, 0])
a2 = np.array([-1, 0, 0, 0, 1])
a3 = np.array([ 0,-2,-1, 1, 1])


A = np.array([a1,
              a2,
              a3])

print('Produto interno de a1 com v1: {}'.format(np.dot(a1,v1)))
print('Produto interno de a1 com v2: {}'.format(np.dot(a1,v2)))
print('Produto interno de a1 com v3: {}'.format(np.dot(a1,v3)))
print('Produto interno de a2 com v1: {}'.format(np.dot(a2,v1)))
print('Produto interno de a2 com v2: {}'.format(np.dot(a2,v1)))
print('Produto interno de a2 com v3: {}'.format(np.dot(a2,v1)))
print('Produto interno de a3 com v1: {}'.format(np.dot(a3,v1)))
print('Produto interno de a3 com v2: {}'.format(np.dot(a3,v2)))
print('Produto interno de a3 com v3: {}'.format(np.dot(a3,v3)))

Produto interno de a1 com v1: 0
Produto interno de a1 com v2: 0
Produto interno de a1 com v3: 0
Produto interno de a2 com v1: 0
Produto interno de a2 com v2: 0
Produto interno de a2 com v3: 0
Produto interno de a3 com v1: 0
Produto interno de a3 com v2: 0
Produto interno de a3 com v3: 0


Verificando que a matriz A leva uma combinação linear de $\mathbf{v}_1$, $\mathbf{v}_2$ e $\mathbf{v}_3$ no vetor nulo de $\mathbb{R}^3$. Seja:
$$
\mathbf{w} = \alpha\mathbf{v}_1 + \beta\mathbf{v}_2 + \gamma\mathbf{v}_3 \\
\alpha, \beta, \gamma \in \mathbb{R}
$$

In [25]:
alpha = np.random.uniform()
beta  = np.random.uniform()
gamma = np.random.uniform()

w = alpha*v1 + beta*v2 + gamma*v3

print('Mapeamento de uma combinação linear aleatória de v1, v2, v3\n')
print('w = {alpha:.4f}*{v1} + {beta:.4f}*{v2} + {gamma:.4f}*{v3}\n'.format(alpha=alpha, v1=v1, beta=beta, v2=v2, gamma=gamma, v3=v3))
print('A.w resulta no vetor nulo de R^3: {}'.format(np.dot(A, w)))

Mapeamento de uma combinação linear aleatória de v1, v2, v3

w = 0.6521*[1 1 0 1 1] + 0.2127*[1 0 1 0 1] + 0.1832*[0 0 1 1 0]

A.w resulta no vetor nulo de R^3: [0. 0. 0.]


Podemos verificar que, por exemplo $\mathbf{e}_1$ da base euclidiana do $\mathbb{R}^5$ é mapeado no espaço imagem como combinação linear de $\mathbf{u}_1$ e $\mathbf{u}_2$:
$$
A\mathbf{e}_1 = [1, -1, 0]^T = -\mathbf{u}_1 + \mathbf{u}_2 \\
$$

In [12]:
e1 = np.array([1, 0, 0, 0, 0])
print(np.dot(A,x))

[ 1 -1  0]


Porém, para mostrar que vale para <b>qualquer</b> vetor mapeado por <b>A</b>, tomemos um vetor $\mathbf{z}$ ortogonal ao plano formado por $\mathbf{u}_1$ e $\mathbf{u}_2$, gerado através de produto vetorial entre estes:
$$
\mathbf{z} = {\mathbf{u}_1} \times {\mathbf{u}_2}
$$
Vamos verificar que vetores aleatórios, quando mapeados por <b>A</b>, também são ortogonais a $\mathbf{z}$.

In [21]:
u1 = np.array([ 0, 1, 1])
u2 = np.array([ 1, 0, 1])

z = np.cross(u1,u2).reshape(3,1)

# Gerando vetores aleatórios em R^5
for i in range(10): 
    x = np.random.uniform(low=-1, high=1, size=(5,1))
    # Cálculo da projeção
    u = np.dot(A,x)
    # Produto interno da projeção com o vetor z ortogonal ao plano u1Xu2
    prod = float(np.dot(u.T,z))
    print('Exemplo aleatório {} (produto interno até 4 casas decimais): {:.4f}'.format(i+1, prod))

Exemplo aleatório 1 (produto interno até 4 casas decimais): 0.0000
Exemplo aleatório 2 (produto interno até 4 casas decimais): 0.0000
Exemplo aleatório 3 (produto interno até 4 casas decimais): 0.0000
Exemplo aleatório 4 (produto interno até 4 casas decimais): 0.0000
Exemplo aleatório 5 (produto interno até 4 casas decimais): 0.0000
Exemplo aleatório 6 (produto interno até 4 casas decimais): 0.0000
Exemplo aleatório 7 (produto interno até 4 casas decimais): 0.0000
Exemplo aleatório 8 (produto interno até 4 casas decimais): -0.0000
Exemplo aleatório 9 (produto interno até 4 casas decimais): 0.0000
Exemplo aleatório 10 (produto interno até 4 casas decimais): 0.0000
