# <font color='blue'>MAI5002 - Fundamentos de Matemática Aplicada</font>

## Segunda Avaliação 06/11/2020

### Prof. Luis Gustavo Nonato  

ICMC-USP

----

## <font color='blue'> Instruções para Avaliação 2</font>
<font color='blue'> Os seguintes passos devem ser seguidos para realizar a avaliação:

1. Assine a lista de presença `lista de presenca` disponível no arquivo que está no diretório _Avaliacao 2/Entrega Avaliacao 2_ do repositório Google Drive
2. Baixe e renomeie o notebook `MAI5002 avaliacao 2.ipynb` com seu nome e número USP
3. Uma vez que tenha concluído a avaliação, faça upload do notebook (renomeado) no diretório _Avaliacao 2/Entrega Avaliacao 2_

O diretório _Avaliacao 2/Entrega Avaliacao 2_ estará aberto para upload até as 17h do dia 08/11. Após esta data e horário não será possível fazer o upload.

Nas questões 1), 2) e 3) você precisa marcar a alternariva correta e também incluir o código Python que calcula o resultado da questão. Para marcar a alternativa que julgue correta, inclua um sinal (X) na frente da mesma. Por exemplo:

a) 123<br>
b) 234 (X)<br>
c) 345<br>
d) 456

Todas as questões da prova valem 2.5 pontos.
</font>

<font color='red'> Não esqueça de renomear o notebook com seu nome e número USP antes de fazer upload no Drive. <br><br>Por exemplo: <br><br> **Gustavo_Nonato_3223813.ipynb** <br><br> Insira também seu nome e número USP na célula abaixo.</font>

---

**Nome:** Bruno Fernandes Bessa de Oliveira

**\#USP:** 5881890

---

### Questão 1) 
Considere a matriz 

$$
\mathbf{A} = 
\begin{bmatrix}
a & 1 & 0 & -1\\
b & 2 & 1 & 0\\
0 & c & d & 1\\
-1 & 0 & 1 & 1
\end{bmatrix}
$$

Qual dos valores de $a,b,c$ e $d$ descritos nas alternativas abaixo torna a matriz $\mathbf{A}$ definida positiva?

a) $a = 1$, $b = 1$, $c = 1$, $d = 1$<br>
b) $a = 1$, $b = 1$, $c = -1$, $d = 2$<br>
c) $a = 3$, $b = 1$, $c = 1$, $d = 2 (X)$<br>
d) $a = 1$, $b = 1$, $c = 1$, $d = 2$<br>

Usemos as propriedades de uma matriz <b>A</b> definida positiva:<br>
* Forma quadrática para qualquer vetor <x> é maior que zero: $\mathbf{x}^\top\mathbf{A}\mathbf{x} > 0$
* Autovalores de A reais são positivos
* det(<b>A</b>) > 0
    
Vamos verificar estas propriedades aplidacas à matriz <b>A</b> para encontrar a alternativa correta.

In [1]:
import numpy as np
from sklearn.decomposition import PCA

In [162]:
#Solução

alternatives = [[1, 1, 1, 1], [1, 1,-1, 2], [3, 1, 1, 2], [1, 1, 1, 2]]

for val in alternatives:
    A = np.array([[val[0],      1,      0,-1],
                  [val[1],      2,      1, 0],
                  [0     , val[2], val[3], 1],
                  [-1    ,      0,      1, 1]])
    # Abaixo calculamos determinante e autovalores da matriz alternativa
    # Além da forma quadrática para vetores aleatórios
    det = np.linalg.det(A)
    w, _ = np.linalg.eig(A)
 
    # Teste para autovalores reais positivos e determinante positivo
    if det > 0 and (not np.any(np.iscomplex(w))) and np.all(w) > 0:
        print('O determinante da matriz A a seguir é zero.')
        print(A)
        print('Seus autovalores são reais positivos:')
        print(w)
        print('\n')
        # Gerando vetores aleatórios em R^4
        # Demonstração de valor de forma quadrática positiva para x arbitrário
        np.set_printoptions(precision=2, suppress=True)
        for i in range(5): 
            x = np.random.uniform(low=-1, high=1, size=(4,1))
            # Cálculo da forma quadrática
            f = np.linalg.multi_dot([x.T,A,x])[0][0]        
            print('Vetor aleatório x = {x}. Fórmula quadrática f=x^T.A.x = {f:.2f} > 0'.format(x=x.T[0], f=f))
        print('\n')
        print('Os valores buscados são: a={val_0}, b={val_1}, c={val_2}, d={val_3}.'.format(val_0=val[0],
                                                                                                  val_1=val[1],
                                                                                                  val_2=val[2],
                                                                                                  val_3=val[3]))

O determinante da matriz A a seguir é zero.
[[ 3  1  0 -1]
 [ 1  2  1  0]
 [ 0  1  2  1]
 [-1  0  1  1]]
Seus autovalores são reais positivos:
[0.1  0.82 3.9  3.18]


Vetor aleatório x = [-0.56  0.8  -0.05  0.37]. Fórmula quadrática f=x^T.A.x = 1.76 > 0
Vetor aleatório x = [-0.22  0.49 -0.2  -0.02]. Fórmula quadrática f=x^T.A.x = 0.29 > 0
Vetor aleatório x = [0.03 0.28 1.   0.47]. Fórmula quadrática f=x^T.A.x = 3.86 > 0
Vetor aleatório x = [ 0.52  0.45 -0.7  -0.32]. Fórmula quadrática f=x^T.A.x = 2.93 > 0
Vetor aleatório x = [-0.29 -0.4   0.69  0.26]. Fórmula quadrática f=x^T.A.x = 1.79 > 0


Os valores buscados são: a=3, b=1, c=1, d=2.


### Questão 2)
Considere o conjunto de pontos definidos nas colunas da matriz $\mathbf{X}$ abaixo. Quais são as coordenadas do ponto dado pela primeira coluna de $\mathbf{X}$ quando projetado na duas primeiras direções principais?

a) 0.33 0.12<br>
b) -0.43  0.03 (X)<br>
c) 0.11 -0.22<br>
d) 1.01 0.56

In [3]:
X = np.array([[ 0.35,  0.69,  0.39, -0.75, -0.86, -0.76, -0.14, -0.85, -0.44, -0.12],
              [-0.07, -0.68,  0.68, -0.26, -0.6 , -0.39,  0.58, -0.85, -0.67, -0.28],
              [ 0.51,  0.83,  0.81, -0.42,  0.83, -0.59, -0.14, -0.91,  0.02,  0.66],
              [ 0.07,  0.78, -0.62, -0.53, -1.00,  0.53,  0.32,  0.85, -0.06, -0.84],
              [-0.14,  0.87,  0.53,  0.70, -0.97, -0.07, -0.79, -0.42,  0.45, -0.29]])

Em vez de calcularmos PCA para a matrix <b>X</b>, usaremos a vantagem da decomposição em SVD:

$$\mathbf{A}=\mathbf{U}\Sigma\mathbf{V}^\top$$

que produz uma matrix <b>U</b> cujas colunas são os autovetores da matriz de covariância dos pontos de <b>X</b>: $\mathbf{A}\mathbf{A}^\top$: ou seja, se tivermos o SVD da matriz, teremos as direções principais dadas por <b>U</b>.

In [163]:
# Solução

# Calculando SVD
U, Sigma, V_T = np.linalg.svd(X)
p = X[:, 0] # ponto dado pela primeira coluna de X

print('A projeção do ponto p em U é dada por (tomar DUAS PRMEIRAS coordenadas):')
print(np.dot(U.T, p))

A projeção do ponto p em U é dada por (tomar DUAS PRMEIRAS coordenadas):
[-0.43  0.03  0.07  0.47 -0.01]


### Questão 3)
Considere a matriz $\mathbf{H}$ abaixo. Encontre a matriz com metade do posto de $\mathbf{H}$ que melhor aproxima $\mathbf{H}$. Qual o erro de aproximação na norma $L^2$?

a) Erro $\approx$ 230.54<br>
b) Erro $\approx$ 380.13<br>
c) Erro $\approx$ 630.18<br>
d) Erro $\approx$ 410.83 (X)<br>

In [65]:
H = np.array([[4, 0, 3, 9, 1, 1, 4, 5, 2, 0, 6, 8, 1, 8, 1, 0, 9, 5, 0, 2],
 [7, 3, 3, 9, 5, 4, 6, 5, 6, 4, 0, 0, 9, 8, 5, 2, 5, 7, 5, 8],
 [7, 0, 7, 7, 1, 7, 0, 5, 8, 8, 0, 8, 5, 0, 3, 2, 8, 7, 8, 8],
 [0, 5, 8, 9, 7, 4, 7, 2, 8, 1, 8, 3, 8, 7, 7, 7, 3, 6, 0, 6],
 [3, 6, 3, 6, 2, 4, 5, 6, 1, 3, 2, 3, 7, 6, 4, 4, 8, 4, 9, 5],
 [2, 3, 1, 0, 4, 4, 0, 2, 2, 5, 5, 7, 6, 2, 9, 6, 0, 8, 9, 7],
 [7, 7, 3, 7, 1, 8, 0, 6, 8, 7, 1, 4, 2, 8, 3, 5, 2, 8, 2, 1],
 [6, 2, 5, 9, 4, 6, 9, 5, 8, 5, 2, 7, 6, 9, 9, 4, 3, 6, 1, 1],
 [8, 2, 5, 2, 0, 0, 1, 2, 9, 2, 6, 7, 9, 6, 6, 9, 3, 6, 7, 7],
 [9, 6, 4, 4, 8, 1, 8, 8, 3, 0, 4, 2, 0, 2, 6, 7, 3, 7, 3, 3]])

A matriz <b>H</b> tem posto 10. Devemos criar uma matriz aproximada pela decomposição de posto reduzido via SVD utilizando os r=5 primeiros elementos da decomposição. 

$$
H_{red} = \mathbf{U}_r\Sigma_r\mathbf{V}_r^\top, r=5
$$

Para calcular o erro da aproximação norma $L^2$ simplesmente calculamos a diferença nas normas das matrizes original $H$ e aproximada de posto reduzido $H_{red}$


In [164]:
# Solução

rank = np.linalg.matrix_rank(H)
# Também seria possível obter essa dimensão pelo número de elementos da matriz Sigma do SVD.
print('Posto da matriz H: rank(H)={rank} e a matriz de posto reduzido H_red terá posto {rank_red}.'.format(rank=rank, rank_red=rank/2))

# SVD de H
U, Sigma, V_T = np.linalg.svd(H)
rank_red = int(rank/2)

# Cálculo da aproximação
H_red = np.linalg.multi_dot([U[:,:rank_red],
                             np.diag(Sigma[:rank_red]),
                             V_T[:rank_red,:]])
# Cálculo do erro
L2 = np.linalg.norm(H.ravel() - H_red.ravel())**2 

print('A matriz de posto reduzido H_red é:')
print(H_red)
print('O erro da aproximação de posto reduzido é {L2:.2f}.'.format(L2=L2))

Posto da matriz H: rank(H)=10 e a matriz de posto reduzido H_red terá posto 5.0.
A matriz de posto reduzido H_red é:
[[ 2.89  0.16  4.28  9.8   1.39  1.93  5.59  4.2   3.13  0.61  3.16  4.62
   3.87  7.12  0.95 -0.54  8.98  3.08  0.65  3.05]
 [ 6.49  3.95  4.57  7.89  4.03  4.28  5.52  6.26  5.24  3.59  3.06  4.83
   5.2   6.3   5.16  4.18  6.27  6.93  4.86  5.1 ]
 [ 7.28  1.26  4.24  6.48 -0.74  6.5  -0.78  5.2   6.6   7.88  0.16  7.91
   6.03  3.93  3.01  2.18  7.68  7.17  8.97  7.01]
 [ 2.64  3.64  6.09  7.73  5.57  2.22  7.61  2.37  7.59  0.46  7.93  4.84
   7.96  9.12  8.08  7.12  2.49  6.03  0.32  4.51]
 [ 5.73  3.09  3.51  5.88  3.61  2.38  4.74  6.    2.21  2.31  2.89  4.28
   5.    3.91  4.09  3.28  7.49  5.8   7.24  6.38]
 [ 4.18  3.34  2.98 -0.25  2.97  2.53  0.31  1.92  4.61  3.86  3.8   4.58
   7.17  1.2   7.24  7.43  0.58  6.33  8.97  7.51]
 [ 7.61  4.51  3.83  7.05  2.11  7.99  2.1   5.59  8.73  7.47 -0.67  4.21
   2.53  6.02  4.53  3.9   1.52  7.39  1.74  1.33]
 [ 5.84 

### Questão 4)
Construa uma transformação linear $\mathbf{A}:\mathbb{R}^3\rightarrow\mathbb{R}^5$ que leve os vetores ortogonais $\mathbf{x}_1=[1,1,1]$, $\mathbf{x}_2=[1,-1,0]$ e $\mathbf{x}_3=[1,1,-2]$ nos vetores ortogonais $\mathbf{y}_1=[1,0,1,0,1]$, $\mathbf{y}_2 = [1,0,-1,1,0]$ e $\mathbf{y}_3=[1,1,0,-1,-1]$, respectivamente, ou seja

$$
\mathbf{A}\mathbf{x}_1=\mathbf{y}_1\\
\mathbf{A}\mathbf{x}_2=\mathbf{y}_2\\
\mathbf{A}\mathbf{x}_3=\mathbf{y}_3\\
$$

**Dica**: Lembre-se da interpretação de transformações lineares via SVD.

In [103]:
x1 = np.array([1,1,1])
x2 = np.array([1,-1,0])
x3 = np.array([1,1,-2])

y1 = np.array([1,0,1,0,1])
y2 = np.array([1,0,-1,1,0])
y3 = np.array([1,1,0,-1,-1])

Podemos construir uma transformação linear <b>A</b> através de SVD. Para isso, consideraremos a propriedade de uma transformação linear ser capaz mapear vetores ortogonais de uma base $x$ no espaço $\mathbb{R}^3$ em vetores também ortogonais de uma base $y$ no espaço $\mathbb{R}^5$.<br>
Dada a diferença de dimensionalidade entre os espaços mencionados, dado o Teorema do Núcleo e da Imagem, a transformaçao desejada terá 3 colunas LI e duas colunas que poderão ser preenchidas por colunas LD.<br>
Dado que obteremos $\mathbf{A}=\mathbf{U}\Sigma\mathbf{V}^\top$ através de SVD, as colunas LD de $A$ serão dadas pelo preenchimento <b>com zero </b>dos últimos altovetores de $U$, autovalores de $\Sigma$ e vetores de $\mathbf{V}^\top$, dada a diferença de dimensionalidade, de acordo com a fórmula abaixo:

$$
\left[
\begin{array}{ccc}
 & & \\
 & \mathbf{A} & \\ 
  & & \\
  & & \\
  & & \\
  & & 
\end{array}\right]= 
\left[\begin{array}{ccc|ccc}
 & & & | & & | \\
 & \mathbf{U} & & | & \cdots & |\\ 
 & & & | & & | \\
  & & & | & & | \\
   & & & | & & | \\
    & & & | & & | 
\end{array}\right]
\left[\begin{array}{ccc}
 & & \\
 & \mathbf{\Sigma} & \\ 
 & & \\\hline
0 & &  \\
 & \ddots &  \\
 & & 0
\end{array}\right]
\left[
\begin{array}{ccc}
 & & \\
 & \mathbf{V}^\top & \\ 
  & & 
\end{array}\right]
$$

Para fazer uso de SVD para criar a matriz $A$ ainda devemos calcular os fatores de escala entre os vetores das baeses da transformação, dados pelas raízes dos autovetores de $\mathbf{A}^\top\mathbf{A}$, na diagonal da matriz $\Sigma$. Neste caso, serão dados pelas razões das <b>normas</b> dos vetores da base.
$$
\mathbf{y}_{normalizado}=(\sqrt{\lambda_1}\mathbf{v}_1^\top\mathbf{x}_{normalizado})
\begin{bmatrix}
| \\ \mathbf{u}_1 \\ |
\end{bmatrix}+\cdots+
(\sqrt{\lambda_n}\mathbf{v}_n^\top\mathbf{x}_{normalizado})
\begin{bmatrix}
| \\ \mathbf{u}_n \\ |
\end{bmatrix}
$$

In [165]:
# Solução

# Calculando as normas dos vetores das bases:
norm_x1 = np.linalg.norm(x1)
norm_x2 = np.linalg.norm(x2)
norm_x3 = np.linalg.norm(x3)
norm_y1 = np.linalg.norm(y1)
norm_y2 = np.linalg.norm(y2)
norm_y3 = np.linalg.norm(y3)

# Montando as matrize U e V_T:
U = np.zeros((5,5))
U[:,0] = y1/norm_y1
U[:,1] = y2/norm_y2
U[:,2] = y3/norm_y3
U[:,3] = np.zeros(np.size(y1))
U[:,4] = np.zeros(np.size(y1))

V_T = np.zeros((5,3))
V_T[0,:] = x1/norm_x1
V_T[1,:] = x2/norm_x2
V_T[2,:] = x3/norm_x3
V_T[3,:] = np.zeros(np.size(x1))
V_T[4,:] = np.zeros(np.size(x1))

# Calculando fatores de escala na matriz diagonal:
# Últimas posiçoes preenchidas com zero por n construção
Sigma = np.zeros((5))
Sigma[0] = (norm_y1/norm_x1)**2
Sigma[1] = (norm_y2/norm_x2)**2
Sigma[2] = (norm_y3/norm_x3)**2
Sigma = np.diag(np.sqrt(Sigma))

np.set_printoptions(precision=2, suppress=True)
print('Dimensões das matrizes calculadas: U:{U} Sigma:{Sigma} V_T:{V_T}'.format(U=U.shape, 
                                                                                Sigma=Sigma.shape, 
                                                                                V_T=V_T.shape))


# Calculando a matriz A:
A = np.linalg.multi_dot([U, Sigma, V_T])
print('Matriz A = U.Sigma.V_T:')
print(A)

print('\n')
print('Verificando o mapeamento inicial:')
print('y1 = {y} = A.x1 = A.{x} = {y_calc}'.format(y=y1, x=x1, y_calc=np.dot(A,x1)))
print('y2 = {y} = A.x2 = A.{x} = {y_calc}'.format(y=y2, x=x2, y_calc=np.dot(A,x2)))
print('y3 = {y} = A.x3 = A.{x} = {y_calc}'.format(y=y3, x=x3, y_calc=np.dot(A,x3)))

Dimensões das matrizes calculadas: U:(5, 5) Sigma:(5, 5) V_T:(5, 3)
Matriz A = U.Sigma.V_T:
[[ 1.    0.    0.  ]
 [ 0.17  0.17 -0.33]
 [-0.17  0.83  0.33]
 [ 0.33 -0.67  0.33]
 [ 0.17  0.17  0.67]]


Verificando o mapeamento inicial:
y1 = [1 0 1 0 1] = A.x1 = A.[1 1 1] = [ 1.  0.  1. -0.  1.]
y2 = [ 1  0 -1  1  0] = A.x2 = A.[ 1 -1  0] = [ 1.  0. -1.  1.  0.]
y3 = [ 1  1  0 -1 -1] = A.x3 = A.[ 1  1 -2] = [ 1.  1.  0. -1. -1.]


Defina a variável que armazena a matriz calcula com a letra `A` e rode o código abaixo. O resultado deve ser 

```python
A matrix calculada está corret? True
```

In [161]:
tol = 1.0e-9

e = np.zeros(3)
e[0] = np.linalg.norm(np.dot(A,x1)-y1)
e[1] = np.linalg.norm(np.dot(A,x2)-y2)
e[2] = np.linalg.norm(np.dot(A,x3)-y3)

print('A matrix calculada está corret?',np.all(np.sum(e) < tol))

A matrix calculada está corret? True
