# <font color='blue'>MAI5002 - Fundamentos de Matemática Aplicada</font>

## <font color='blue'>Ortogonalidade - Solução dos Exercícios </font>

### Material produzido por Luis Gustavo Nonato 

ICMC-USP

----

In [22]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)
O arquivo `teste_matriz.dat` (disponível para download no repositório) armazena uma matriz com 10 linhas e 7 colunas. Leia a matriz e verifique se as colunas são ortogonais.

In [6]:
# Solução


[[ 1.  0.  0.  0. -0. -0. -0.]
 [ 0.  1.  0. -0. -0.  0. -0.]
 [ 0.  0.  1.  0. -0.  0. -0.]
 [ 0. -0.  0.  1. -0. -0.  0.]
 [-0. -0. -0. -0.  1. -0. -0.]
 [-0.  0.  0. -0. -0.  1.  0.]
 [-0. -0. -0.  0. -0.  0.  1.]]


### Exercício 2)
Construa uma transformação linear que leva vetores de $\mathbb{R}^5$ para o sub-espaço $\mathcal{S}$ gerado pelos vetores $[1,1,1]$ e $[0,0,1]$ em $\mathbb{R}^3$. Verificar que a transformação obtida está realizando o mapeamento corretamente.

In [12]:
# Solução

[[1. 0. 1. 1. 2.]
 [1. 0. 1. 1. 2.]
 [1. 1. 0. 2. 1.]]


### Exercício 3)
Construa uma transformação linear $\mathbf{A}:\mathbb{R}^5\rightarrow\mathbb{R}^3$ de modo que os vetores $[1,1,0,0,0]$ e $[0,1,0,0,0]$ sejam o complemento ortogonal do espaço linha.
Vefique que a transformação encontrada está correta.

In [19]:
# Solução



[0 0 0]
[0 0 0]


### Exercício 4)
Construa uma transformação linear que mapeie o hiperplano $x_1+x_2+x_3+x_4+x_5=0$ para o  espaço $\mathbb{R}^2$ e visualize o resultado da transformação para alguns pontos gerados sobre o hiperplano.

In [26]:
# Solução


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


### Exercício 5)
No exercício anterior, podemos afirmar que qualquer ponto  (diferente de $[0,0]$) sobre o hiperplano $x_1+x_2+x_3+x_4+x_5=0$ será mapeado para um ponto diferente de $[0,0]$ em $\mathbb{R}^2$? Em caso afirmativo justifique sua resposta, em caso negativo, dê exemplo de um ponto sobre no hiperplano que é mapeado na origem do espaço $\mathbb{R}^2$.

In [33]:
# Solução

ponto z=a*y1+b*y2 pertence ao plano? True
A imagem de z= [-1.5  1.  -1.5  1.   1. ] pela transformação A é [0. 0.]


### Exercício 6) 
Considere a transformação linear dada pela matriz 
$$
\left(\begin{array}{ccccccc}
3 & 9 & 6 & 6 & 9 & 3 & 1\\
2 & 0 & 9 & 2 & 0 & 5 & 3\\
0 & 0 & 1 & 0 & 1 & 0 & 2
\end{array}\right)
$$

a) Qual a dimensão do núcleo da transformação?<br>
b) Encontre uma base para o espaço núcleo.<br>
c) Verifique que a base encontrada está gerando o  núcleo.

In [14]:
# Solução
B = np.asarray([[3, 9, 6, 6, 9, 3, 1],
                [2, 0, 9, 2, 0, 5, 3],
                [0, 0, 1 , 0, 1, 0, 2]])



Determinante de
 [[3 9 6]
 [2 0 9]
 [0 0 1]]  =  -17.999999999999996

Dimensão do núcleo de
 [[3 9 6 6 9 3 1]
 [2 0 9 2 0 5 3]
 [0 0 1 0 1 0 2]] 
 é 4


In [17]:
# Verificando que os vetores calculados estão no núcleo

np.set_printoptions(precision=5,suppress=True)
print(np.dot(B,base))

[[ 0. -0.  0. -0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


### Exercício 7)
Sabemos que para toda transformação linear $\mathbf{X}$, os vetores que pertencem ao espaço linha de $\mathbf{X}$ são ortogonais aos vetores que estão no espaço nulo de $\mathbf{X}$.

Considerando a propriedade acima, construa uma transformação linear cujo núcleo (espaço nulo) é gerado pelos vetores $\mathbf{x}_1=[1,1,0,1]$ e $\mathbf{x}_2=[0,1,0,1]$.

### Exercício 8)
Escreva um código para, dada uma base qualquer de um subespaço, encontrar uma base ortonormal para este mesmo subespaço. Teste o seu código para a base dada como colunas da matriz $\mathbf{V}$ gerada no código abaixo. Verifique que a base obtida é de fato ortonormal.

In [1]:
# Solução

[[17  7 10  0 16 14 13 14  0  0]
 [15  6 17  5  3 11 15 19  9  9]
 [ 9 12 19 13  8  8  9 12 17 17]
 [16  5 19  6  0 17  7 16 10  7]
 [ 0  4 14  9  1 19 17  3  1  9]
 [ 9  2 18 11 10 13  0 19  2  1]
 [12  1 14  4 11 16 10 17 14  9]
 [18 12 10 19 13 17  9  1  7  9]
 [ 2 18  1  7 17  4  8 12  5 12]
 [ 4  0 16  0 10  8 13  5 10 19]
 [ 5  3  8 14 12 11  8  0 14 12]
 [ 3 17  6  6 15 13  8 13  1 12]
 [ 6  8 10 16  7  7 11 15  8 11]
 [ 2 15  0 10  8 12  9  0  1 16]
 [ 1 15 18  7  3 15 11 14  2 15]
 [ 0 10 12 18 17 18  0  3  1  9]
 [19  9  1 19 13  9  7 19 12  4]
 [ 7 16  6 17 18 15  1 14  8  0]
 [ 6 13  3 13  3  9  5 18 16 10]
 [10 19  4 13 11  0  1  4 19 17]]


### Exercício 9) 
Considere o espaço gerado pelos vetores $[1,1,1]$ e $[1,0,1]$. Construa uma base ortogonal para este espaço e encontre a projeção de qualquer ponto de $\mathbb{R}^3$ sobre plano gerado pelos vetores ortogonais.